<a href="https://colab.research.google.com/github/SantiBechir/Curso-de-Git/blob/master/arraynp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:

arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr[1] + arr[5]

8

In [10]:
matriz[0,2]

3

In [13]:
arr[1:7]

array([2, 3, 4, 5, 6, 7])

In [14]:
arr[::2]

array([1, 3, 5, 7, 9])

In [15]:
arr[-1]

9

In [16]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])